package com.astrovm.crosstune

/**
 * How Pixel Now Playing words a shared song in each of its languages, taken from its
 * song_action_share_song_text and song_search_query_pattern strings. %1$s is the title and
 * %2$s the artist. The first is the text it shares, the second what it searches Google for.
 */
internal object NowPlayingShares {
    val patterns = listOf(
        "%1\$s by %2\$s" to "%1\$s by %2\$s",
        "\"%1\$s\", %2\$s" to "\"%1\$s\", %2\$s",
        "\"%1\$s\", %2\$s" to "\"%1\$s\", виконавець: %2\$s",
        "\"%1\$s\", %2\$s" to "Песня \"%1\$s\" исполнителя \"%2\$s\"",
        "%1\$s (izpildītājs: %2\$s)" to "%1\$s (izpildītājs: %2\$s)",
        "%1\$s af %2\$s" to "%1\$s af %2\$s",
        "%1\$s av %2\$s" to "%1\$s av %2\$s",
        "%1\$s av %2\$s" to "%1\$s med %2\$s",
        "%1\$s của %2\$s" to "%1\$s của %2\$s",
        "%1\$s de %2\$s" to "%1\$s de %2\$s",
        "%1\$s de la %2\$s" to "%1\$s de la %2\$s",
        "%1\$s de: %2\$s" to "%1\$s de: %2\$s",
        "%1\$s deur %2\$s" to "%1\$s deur %2\$s",
        "%1\$s di %2\$s" to "%1\$s di %2\$s",
        "%1\$s eftir %2\$s" to "%1\$s með %2\$s",
        "%1\$s esitajalt %2\$s" to "%1\$s esitajalt %2\$s",
        "%1\$s izvođača %2\$s" to "%1\$s izvođača %2\$s",
        "%1\$s nga %2\$s" to "%1\$s nga %2\$s",
        "%1\$s ngo-%2\$s" to "%1\$s ngo-%2\$s",
        "%1\$s ni/ng %2\$s" to "%1\$s ni/ng %2\$s",
        "%1\$s od interpreta %2\$s" to "%1\$s od interpreta %2\$s",
        "%1\$s od izvođača %2\$s" to "%1\$s od izvođača %2\$s",
        "%1\$s oleh %2\$s" to "%1\$s oleh %2\$s",
        "%1\$s par %2\$s" to "%1\$s (%2\$s)",
        "%1\$s par %2\$s" to "%1\$s par %2\$s",
        "%1\$s van %2\$s" to "%1\$s van %2\$s",
        "%1\$s wa %2\$s" to "%1\$s wa %2\$s",
        "%1\$s από %2\$s" to "%1\$s από %2\$s",
        "%1\$s од %2\$s" to "%1\$s од %2\$s",
        "%1\$s од извођача %2\$s" to "%1\$s од извођача %2\$s",
        "%1\$s של %2\$s" to "%1\$s של %2\$s",
        "%1\$s از %2\$s" to "%1\$s از %2\$s",
        "%1\$s بصوت %2\$s" to "%1\$s بصوت %2\$s",
        "%1\$s ଦ୍ୱାରା %2\$s" to "%2\$s ଦ୍ଵାରା %1\$s",
        "%1\$s ಅವರಿಂದ %2\$s" to "%1\$s ಅವರಿಂದ %2\$s",
        "%1\$s โดย %2\$s" to "%1\$s โดย %2\$s",
        "%1\$s ໂດຍ %2\$s" to "%1\$s ໂດຍ %2\$s",
        "%1\$s በ%2\$s" to "%1\$s በ%2\$s",
        "%1\$s ដោយ %2\$s" to "%1\$s ដោយ %2\$s",
        "%1\$s – %2\$s" to "%1\$s (%2\$s)",
        "%1\$s – %2\$s" to "%2\$s – %1\$s",
        "%1\$s, %2\$s" to "%1\$s, %2\$s",
        "%1\$s, %2\$s എന്നതിലൂടെ" to "%2\$s-ന്റെ %1\$s",
        "%1\$s, izvajalec: %2\$s" to "%1\$s, izvajalec: %2\$s",
        "%1\$s, შემსრულებელი: %2\$s" to "%1\$s, შემსრულებელი: %2\$s",
        "%1\$s（%2\$s）" to "%1\$s（%2\$s）",
        "%2\$s tərəfindən %1\$s" to "%2\$s tərəfindən %1\$s",
        "%2\$s аткаруусундагы %1\$s деген ыр" to "%2\$s аткаруусундагы %1\$s деген ыр",
        "%2\$s орындайтын %1\$s" to "%2\$s орындайтын %1\$s",
        "%2\$s کا %1\$s" to "%2\$s کا %1\$s",
        "%2\$s का %1\$s" to "%2\$s का %1\$s",
        "%2\$s को %1\$s" to "%2\$s को %1\$s",
        "%2\$s चे %1\$s" to "%2\$s चे %1\$s",
        "%2\$s এর %1\$s" to "%2\$s এর %1\$s",
        "%2\$s ਵੱਲੋਂ %1\$s" to "%2\$s ਵੱਲੋਂ %1\$s",
        "%2\$s இன் %1\$s" to "%2\$s இன் %1\$s",
        "%2\$s ద్వారా %1\$s" to "%2\$s ద్వారా %1\$s",
        "%2\$s ၏ %1\$s" to "%2\$s ၏ %1\$s",
        "%2\$s – %1\$s" to "%2\$s – %1\$s",
        "%2\$s, %1\$s" to "%1\$s, %2\$s",
        "%2\$s-н %1\$s" to "%2\$s-н %1\$s",
        "%2\$s: %1\$s" to "%2\$s: %1\$s",
        "%2\$sৰ %1\$s" to "%2\$sৰ %1\$s",
        "%2\$sનું %1\$s" to "%2\$s દ્વારા %1\$s",
        "%2\$sගේ %1\$s" to "%2\$sගේ %1\$s",
        "%2\$s的《%1\$s》" to "%2\$s的《%1\$s》",
        "%2\$s의 %1\$s" to "%2\$s의 %1\$s",
        "«%1\$s», %2\$s" to "«%1\$s», %2\$s",
        "„%1\$s“ („%2\$s“)" to "„%1\$s“ („%2\$s“)",
        "„%1\$s“ von %2\$s" to "„%1\$s“ von %2\$s",
        "„%1\$s“ на %2\$s" to "%1\$s на %2\$s",
        "「%1\$s」，演出者：%2\$s" to "「%1\$s」，演出者：%2\$s"
    )
}
